services:
  mongo:
    image: mongo:7
    container_name: eco_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8
    container_name: eco_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecofinance
      MYSQL_USER: eco_user
      MYSQL_PASSWORD: eco_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: eco_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  prometheus:
    image: prom/prometheus:latest
    container_name: eco_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: eco_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  expensesservice:
    build:
      context: ../services/ExpensesService
      dockerfile: Dockerfile
    container_name: eco_expensesservice
    ports:
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=EcoFinanceDb
    depends_on:
      - mongo

  userservice:
    build:
      context: ../services/UserService
      dockerfile: Dockerfile
    container_name: eco_userservice
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=eco_mysql;port=3306;database=ecofinance;user=eco_user;password=eco_pass
      - Jwt__Key=YOUR_SUPER_SECRET_KEY_HERE_MIN_32_CHARS
      - Jwt__Issuer=EcoFinance
      - Jwt__Audience=EcoFinance
    depends_on:
      - mysql

volumes:
  mongo_data:
  mysql_data: